export const NOW_UPDATE_INTERVAL_ERROR_CONTENT = 500;
export const NOW_UPDATE_INTERVAL_DEVICE_SENSORS = 1000;

export const REFRESH_INTERVAL_HOME = 60_000;
export const REFRESH_INTERVAL_APPLIANCE_PAGE = REFRESH_INTERVAL_HOME;
export const REFRESH_INTERVAL_DEVICE_PAGE = REFRESH_INTERVAL_HOME;

export const SWIPE_THRESHOLD_DISTANCE_AC_TEMPERATURE = 1;
